create table if not exists profile (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    role varchar(255) not null,
    location varchar(255) not null,
    origin varchar(255) not null,
    email varchar(255) not null,
    email_href varchar(255) not null,
    phone varchar(255) not null,
    phone_href varchar(255) not null,
    linkedin varchar(255) not null,
    github varchar(255) not null,
    resume varchar(255) not null,
    summary varchar(2000) not null
);

create table if not exists projects (
    id bigint generated by default as identity primary key,
    slug varchar(255) not null unique,
    name varchar(255) not null,
    category varchar(255) not null,
    org varchar(255) not null,
    period varchar(255) not null,
    summary varchar(2000) not null,
    outcome varchar(500),
    app_store varchar(255),
    play_store varchar(255),
    featured boolean not null,
    sort_order integer not null
);

create table if not exists project_points (
    project_id bigint not null,
    point varchar(500),
    position integer not null,
    primary key (project_id, position),
    constraint fk_project_points_project foreign key (project_id) references projects (id)
);

create table if not exists project_stack (
    project_id bigint not null,
    item varchar(255),
    position integer not null,
    primary key (project_id, position),
    constraint fk_project_stack_project foreign key (project_id) references projects (id)
);

create table if not exists experience (
    id bigint generated by default as identity primary key,
    role varchar(255) not null,
    org varchar(255) not null,
    place varchar(255) not null,
    period varchar(255) not null,
    sort_order integer not null
);

create table if not exists experience_points (
    experience_id bigint not null,
    point varchar(500),
    position integer not null,
    primary key (experience_id, position),
    constraint fk_experience_points_experience foreign key (experience_id) references experience (id)
);

create table if not exists education (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    org varchar(255) not null,
    period varchar(255) not null,
    sort_order integer not null
);

create table if not exists certifications (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    href varchar(400) not null,
    sort_order integer not null
);
