create table if not exists admin_sessions (
    id varchar(64) primary key,
    username varchar(120) not null,
    device_id varchar(128) not null,
    refresh_token_hash varchar(64) not null,
    expires_at timestamp(6) with time zone not null
);

create table if not exists audit_events (
    id bigint generated by default as identity primary key,
    occurred_at timestamp(6) with time zone not null,
    actor varchar(255) not null,
    action varchar(64) not null,
    resource varchar(500) not null
);
